### ISSUE TITLE
Entitlement checker bugs

### ISSUE THREAD

**Issue by bkrodgers** [MonsantoCo/glass-key#1]
The entitlement checking logic appears to have some bugs.  I've created a branch with a currently failing unit test:

https://github.com/MonsantoCo/glass-key/blob/entitlement-authorizer-bug/glass-key-common/src/test/scala/glasskey/resource/validation/EntitlementAuthorizerSpec.scala

Note that some of these bugs result in people getting access when they should not.

I haven't written every combination into the test yet, but I hit some of the big ones that are causing me difficulty right now.  I'm happy to work on fixing them myself, but I wanted to check with you first.  Take a look at my comments on the TODOs and let me know what you think.

**Comment by larryboymi** [comment]
Should be fixed with https://github.com/MonsantoCo/glass-key/commit/f39c98fbcb0d5664f86279a8b6fc28581b20521b , thanks for the find.
